// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VeterinariaASPWebApi.Models;

#nullable disable

namespace VeterinariaASPWebApi.Migrations
{
    [DbContext(typeof(VeterinariaContext))]
    partial class VeterinariaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("colaboradores_id_seq")
                .HasMax(9999L);

            modelBuilder.HasSequence("detalles_historias_clinicas_id_seq")
                .HasMax(9999L);

            modelBuilder.HasSequence("historias_clinicas_id_seq")
                .HasMax(9999L);

            modelBuilder.HasSequence("mascotas_id_seq")
                .HasMax(9999L);

            modelBuilder.HasSequence("usuarios_id_seq")
                .HasMax(9999L);

            modelBuilder.Entity("VeterinariaASPWebApi.Models.Colaborador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("apellido");

                    b.Property<string>("Cargo")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("cargo");

                    b.Property<int?>("DocumentoIdentificacion")
                        .HasColumnType("integer")
                        .HasColumnName("documento_identificacion");

                    b.Property<string>("Especialidad")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("especialidad");

                    b.Property<string>("Nombre")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nombre");

                    b.Property<string>("TipoDocumento")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("tipo_documento");

                    b.HasKey("Id")
                        .HasName("colaboradores_pkey");

                    b.ToTable("colaboradores", (string)null);
                });

            modelBuilder.Entity("VeterinariaASPWebApi.Models.DetallesHistoriasClinica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Alimentacion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("alimentacion");

                    b.Property<int?>("ColaboradorId")
                        .HasColumnType("integer")
                        .HasColumnName("colaborador_id");

                    b.Property<DateTime?>("FechaHora")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_hora");

                    b.Property<float?>("FrecuenciaCardiaca")
                        .HasColumnType("real")
                        .HasColumnName("frecuencia_cardiaca");

                    b.Property<float?>("FrecuenciaRespiratoria")
                        .HasColumnType("real")
                        .HasColumnName("frecuencia_respiratoria");

                    b.Property<string>("Habitad")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("habitad");

                    b.Property<int?>("HistoriaClinicaId")
                        .HasColumnType("integer")
                        .HasColumnName("historia_clinica_id");

                    b.Property<string>("Observacion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("observacion");

                    b.Property<float?>("Peso")
                        .HasColumnType("real")
                        .HasColumnName("peso");

                    b.Property<string>("Temperatura")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("temperatura");

                    b.HasKey("Id")
                        .HasName("detalles_historias_clinicas_pkey");

                    b.HasIndex("ColaboradorId");

                    b.HasIndex("HistoriaClinicaId");

                    b.ToTable("detalles_historias_clinicas", (string)null);
                });

            modelBuilder.Entity("VeterinariaASPWebApi.Models.HistoriasClinica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("FechaCreacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_creacion");

                    b.Property<int?>("MascotaId")
                        .HasColumnType("integer")
                        .HasColumnName("mascota_id");

                    b.HasKey("Id")
                        .HasName("historias_clinicas_pkey");

                    b.HasIndex("MascotaId");

                    b.ToTable("historias_clinicas", (string)null);
                });

            modelBuilder.Entity("VeterinariaASPWebApi.Models.Mascota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nombre");

                    b.Property<string>("Raza")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("raza");

                    b.Property<string>("Sexo")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("sexo");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("macotas_pkey");

                    b.HasIndex("UsuarioId");

                    b.ToTable("mascotas", (string)null);
                });

            modelBuilder.Entity("VeterinariaASPWebApi.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("apellido");

                    b.Property<int?>("DocumentoIdentificacion")
                        .HasColumnType("integer")
                        .HasColumnName("documento_identificacion");

                    b.Property<string>("Estado")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nombre");

                    b.Property<int?>("Sexo")
                        .HasColumnType("integer")
                        .HasColumnName("sexo");

                    b.Property<string>("TipoDocumento")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("tipo_documento");

                    b.HasKey("Id")
                        .HasName("usuario_pkey");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("VeterinariaASPWebApi.Models.DetallesHistoriasClinica", b =>
                {
                    b.HasOne("VeterinariaASPWebApi.Models.Colaborador", "Colaborador")
                        .WithMany("DetallesHistoriasClinicas")
                        .HasForeignKey("ColaboradorId")
                        .HasConstraintName("detalles_historias_clinicas_colaborador_id_fkey");

                    b.HasOne("VeterinariaASPWebApi.Models.HistoriasClinica", "HistoriaClinica")
                        .WithMany("DetallesHistoriasClinicas")
                        .HasForeignKey("HistoriaClinicaId")
                        .HasConstraintName("detalles_historias_clinicas_historia_clinica_id_fkey");

                    b.Navigation("Colaborador");

                    b.Navigation("HistoriaClinica");
                });

            modelBuilder.Entity("VeterinariaASPWebApi.Models.HistoriasClinica", b =>
                {
                    b.HasOne("VeterinariaASPWebApi.Models.Mascota", "Mascota")
                        .WithMany("HistoriasClinicas")
                        .HasForeignKey("MascotaId")
                        .HasConstraintName("fk_historia_clinica_mascotas");

                    b.Navigation("Mascota");
                });

            modelBuilder.Entity("VeterinariaASPWebApi.Models.Mascota", b =>
                {
                    b.HasOne("VeterinariaASPWebApi.Models.Usuario", "Usuario")
                        .WithMany("Mascota")
                        .HasForeignKey("UsuarioId")
                        .HasConstraintName("macotas_usuario_id_fkey");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("VeterinariaASPWebApi.Models.Colaborador", b =>
                {
                    b.Navigation("DetallesHistoriasClinicas");
                });

            modelBuilder.Entity("VeterinariaASPWebApi.Models.HistoriasClinica", b =>
                {
                    b.Navigation("DetallesHistoriasClinicas");
                });

            modelBuilder.Entity("VeterinariaASPWebApi.Models.Mascota", b =>
                {
                    b.Navigation("HistoriasClinicas");
                });

            modelBuilder.Entity("VeterinariaASPWebApi.Models.Usuario", b =>
                {
                    b.Navigation("Mascota");
                });
#pragma warning restore 612, 618
        }
    }
}
